-- MySQL Script generated by MySQL Workbench
-- Fri Aug 21 21:53:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema corpo133_sii
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `intermediarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intermediarios` ;

CREATE TABLE IF NOT EXISTS `intermediarios` (
  `IdusuarioIntermediario` INT NOT NULL AUTO_INCREMENT,
  `Laboratorio` VARCHAR(45) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `ApPaterno` VARCHAR(45) NOT NULL,
  `ApMaterno` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL,
  `Telof` VARCHAR(45) NOT NULL,
  `Extension` VARCHAR(8) NOT NULL,
  `Celular` VARCHAR(75) NOT NULL,
  `Status` SMALLINT(2) NOT NULL,
  `NomReg` VARCHAR(75) NOT NULL,
  `FechaReg` DATE NOT NULL,
  `NomEdit` VARCHAR(75) NOT NULL,
  `FechaEdit` DATE NOT NULL,
  PRIMARY KEY (`IdusuarioIntermediario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

CREATE TABLE IF NOT EXISTS `clientes` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `CliLab` VARCHAR(75) NOT NULL,
  `RznScl` VARCHAR(175) NOT NULL,
  `IdInt` INT NOT NULL,
  `Status` TINYINT(2) NOT NULL,
  `CliNomReg` VARCHAR(125) NOT NULL,
  `CliDateReg` DATE NOT NULL,
  `CliNomMod` VARCHAR(125) NOT NULL,
  `CliDateMod` DATE NOT NULL,
  PRIMARY KEY (`IdCliente`, `IdInt`),
  INDEX `fk_clientes_intermediarios1_idx` (`IdInt` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_intermediarios1`
    FOREIGN KEY (`IdInt`)
    REFERENCES `intermediarios` (`IdusuarioIntermediario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interfaz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `interfaz` ;

CREATE TABLE IF NOT EXISTS `interfaz` (
  `IdClientePapa` INT NOT NULL,
  `NombreCliente` VARCHAR(45) NULL,
  `Intermediario` VARCHAR(45) NULL,
  `Status` TINYINT(2) NULL,
  `EdoRepublica` VARCHAR(45) NULL,
  `TipoCliente` VARCHAR(45) NULL,
  PRIMARY KEY (`IdClientePapa`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `clientesirlab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientesirlab` ;

CREATE TABLE IF NOT EXISTS `clientesirlab` (
  `IdCliente` INT NOT NULL,
  `RFC` VARCHAR(45) NOT NULL,
  `AddInf` VARCHAR(255) NOT NULL,
  `Calle` VARCHAR(125) NOT NULL,
  `NumExt` VARCHAR(5) NOT NULL DEFAULT 'S/N',
  `NumInt` VARCHAR(5) NOT NULL DEFAULT 'S/N',
  `Col` VARCHAR(75) NOT NULL DEFAULT 'NA',
  `CP` BIGINT(7) NOT NULL,
  `Loc` VARCHAR(75) NOT NULL DEFAULT 'NA',
  `Mun` VARCHAR(75) NOT NULL,
  `Cd` VARCHAR(75) NOT NULL DEFAULT 'NA',
  `Edo` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`IdCliente`),
  CONSTRAINT `fk_clientesirlab_clientes1`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `clientes` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
